import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowRight,
  IconBarcode,
  IconBell,
  IconBold,
  IconBox,
  IconBrandTwitter,
  IconBrightness,
  IconBuilding,
  IconBuildingWarehouse,
  IconCalendar,
  IconCategory,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconClipboardList,
  IconAlertTriangleFilled,
  IconCircle,
  IconCircleCheck,
  IconCirclePlus,
  IconCircleX,
  IconClipboardText,
  IconClock,
  IconCode,
  IconCoin,
  IconCommand,
  IconCreditCard,
  IconDeviceLaptop,
  IconDots,
  IconDownload,
  IconDotsVertical,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileDescription,
  IconFilter,
  IconFileText,
  IconFileTypePdf,
  IconFileTypeDoc,
  IconMail,
  IconFileTypeXls,
  IconFileZip,
  IconFolder,
  IconGripVertical,
  IconHelpCircle,
  IconInfoCircle,
  IconItalic,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLayoutSidebar,
  IconLoader2,
  IconLock,
  IconLogin,
  IconLogout,
  IconMessage,
  IconMinus,
  IconMoon,
  IconMusic,
  IconPalette,
  IconPaperclip,
  IconPhone,
  IconPhoto,
  IconPrinter,
  IconPizza,
  IconPlus,
  IconProps,
  IconReceiptTax,
  IconRosetteDiscountCheck,
  IconRuler2,
  IconSearch,
  IconSelector,
  IconSend,
  IconSettings,
  IconShare,
  IconSlash,
  IconSparkles,
  IconStack2,
  IconStar,
  IconSun,
  IconTag,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTypography,
  IconUnderline,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconUsers,
  IconVideo,
  IconCrown,
  IconTruckDelivery,
  IconShoppingCart,
  IconAddressBook,
  IconUserDollar,
  IconReceipt2,
  IconReceipt,
  IconGift,
  IconTicket,
  IconTruck,
  IconRefresh,
  IconX,
  IconCashRegister,
  IconScan,
  IconKeyboard,
  IconDiscount2,
  IconPercentage,
  IconHistory,
  IconDeviceFloppy,
  IconArrowBackUp,
  IconLayoutGrid,
  IconBackspace,
  IconSpace,
  IconMoodEmpty,
  IconWallet,
  IconDoorEnter,
  IconDoorExit,
  IconReceiptDollar,
  IconQrcode,
  IconBrandStripe,
  IconDeviceMobileDollar,
  IconWifiOff
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // General
  alertCircle: IconAlertCircle,
  warning: IconAlertTriangle,
  arrowRight: IconArrowRight,
  check: IconCheck,
  checks: IconChecks,
  circleCheck: IconCircleCheck,
  close: IconX,
  clock: IconClock,
  code: IconCode,
  dots: IconDots,
  ellipsis: IconDotsVertical,
  externalLink: IconExternalLink,
  help: IconHelpCircle,
  info: IconInfoCircle,
  spinner: IconLoader2,
  search: IconSearch,
  settings: IconSettings,
  trash: IconTrash,

  // Navigation / Chevrons
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronsDown: IconChevronsDown,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  chevronsUpDown: IconSelector,

  // Layout
  dashboard: IconLayoutDashboard,
  kanban: IconLayoutKanban,
  panelLeft: IconLayoutSidebar,

  // User
  user: IconUser,
  user2: IconUserCircle,
  account: IconUserCircle,
  profile: IconUser,
  employee: IconUserX,
  userPen: IconUserEdit,
  teams: IconUsers,
  company: IconBuilding,
  warehouse: IconBuildingWarehouse,
  currency: IconCoin,
  tax: IconReceiptTax,
  category: IconCategory,
  brand: IconTag,
  unit: IconRuler2,
  customField: IconClipboardList,
  supplier: IconTruckDelivery,
  customer: IconAddressBook,
  saleAgent: IconUserDollar,
  biller: IconReceipt2,
  quotation: IconFileDescription,
  mail: IconMail,
  purchase: IconShoppingCart,
  sale: IconReceipt,
  giftCard: IconGift,
  coupon: IconTicket,
  courier: IconTruck,
  refresh: IconRefresh,
  barcode: IconBarcode,
  printer: IconPrinter,
  pos: IconCashRegister,

  // POS
  scan: IconScan,
  keyboard: IconKeyboard,
  discount: IconDiscount2,
  percentage: IconPercentage,
  history: IconHistory,
  hold: IconDeviceFloppy,
  undo: IconArrowBackUp,
  grid: IconLayoutGrid,
  backspace: IconBackspace,
  space: IconSpace,
  empty: IconMoodEmpty,
  wallet: IconWallet,
  registerOpen: IconDoorEnter,
  registerClose: IconDoorExit,
  receiptDollar: IconReceiptDollar,
  qrcode: IconQrcode,
  gatewayStripe: IconBrandStripe,
  gatewayMobileMoney: IconDeviceMobileDollar,
  offline: IconWifiOff,

  // Brand
  twitter: IconBrandTwitter,
  logo: IconCommand,

  // Communication
  chat: IconMessage,
  notification: IconBell,
  phone: IconPhone,
  video: IconVideo,
  send: IconSend,
  paperclip: IconPaperclip,

  // Files
  page: IconFile,
  post: IconFileText,
  fileTypePdf: IconFileTypePdf,
  fileTypeDoc: IconFileTypeDoc,
  fileTypeXls: IconFileTypeXls,
  fileZip: IconFileZip,
  media: IconPhoto,
  music: IconMusic,

  // Actions
  add: IconPlus,
  edit: IconEdit,
  upload: IconUpload,
  download: IconDownload,
  share: IconShare,
  login: IconLogin,
  logout: IconLogout,
  gripVertical: IconGripVertical,

  // Shapes / Indicators
  circle: IconCircle,
  circleX: IconCircleX,
  plusCircle: IconCirclePlus,
  xCircle: IconCircleX,
  minus: IconMinus,

  // Theme
  sun: IconSun,
  moon: IconMoon,
  brightness: IconBrightness,
  laptop: IconDeviceLaptop,
  palette: IconPalette,

  // Commerce / Plans
  billing: IconCreditCard,
  creditCard: IconCreditCard,
  product: IconBox,
  pro: IconCrown,
  exclusive: IconStar,
  sparkles: IconSparkles,
  badgeCheck: IconRosetteDiscountCheck,
  lock: IconLock,

  // Data / Charts
  trendingDown: IconTrendingDown,
  trendingUp: IconTrendingUp,
  eye: IconEye,
  eyeOff: IconEyeOff,
  adjustments: IconAdjustmentsHorizontal,
  stockCount: IconClipboardList,
  damageStock: IconAlertTriangleFilled,
  filter: IconFilter,

  // Text formatting
  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  text: IconTypography,

  // Toast
  toastSuccess: IconCircleCheck,
  toastInfo: IconInfoCircle,
  toastWarning: IconAlertTriangle,
  toastError: IconCircleX,
  toastLoading: IconLoader2,

  // Misc
  pizza: IconPizza,
  workspace: IconFolder,
  forms: IconClipboardText,
  slash: IconSlash,
  calendar: IconCalendar,
  galleryVerticalEnd: IconStack2,
  moreHorizontal: IconDots
};
